# Generated by Django 4.2.4 on 2023-10-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crap_maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
