# Generated by Django 4.2.6 on 2023-10-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crap_maps', '0002_alter_bathroom_latitude_alter_bathroom_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('bathroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crap_maps.bathroom')),
            ],
        ),
    ]
